### ISSUE TITLE
Granular Loading Indicator

### ISSUE THREAD

**Issue by mjnaderi** [RevereCRE/relay-nextjs#13]
Hi,

Thanks for this great library.

I need more granular control for displaying loading state. I want to display a loading spinner in a child component, not the whole page.

I commented `<Suspense>` from `component.tsx`, but I get a weird error when navigating.

This is the error that was printed in my browser console for "example project":

![image](https://user-images.githubusercontent.com/2115303/119211624-9589e580-bac8-11eb-8e8e-fb3dbc496224.png)

And this is displayed in page:

![image](https://user-images.githubusercontent.com/2115303/119211947-93288b00-baca-11eb-93d0-1c1004270460.png)

The error says "above error", but there is no error printed above.

**Comment by rrdelaney** [comment]
This is a bit difficult to do with how Suspense works. This library loads a query along with the page and lets Relay suspend on client-side navigations. If only part of the page needs data and you don't want to block you can use `useLazyLoadQuery` or create a fallback that works like the rest of the page without that data.

**Comment by rrdelaney** [comment]
Closing as this is pretty much incompatible with how this library works. If you'd like to only show a loading spinner in part of the app you can use `useLazyLoadQuery`. It's not currently possible to say "render the app except for this part".
