### ISSUE TITLE
Does not run queries without an argument on first page load

### ISSUE THREAD

**Issue by AngelLoredoAlvarez** [RevereCRE/relay-nextjs#17]
First of all, ¡this is and incredible library!, it works beautifully.

But there is a wired problem (or maybe I'm configured something wrong), the issue is, when I try to load a query with an argument, like an ID or something to filter the query, it works perfectly when I reload the page or start to navigate across the APP, but, when I run a simple querie, without arguments, it throws a null value when the page is reloaded, but here is the thing, when I start to navigate in the APP, the querie without arguments works, and I get the information required.

I'm very new in this of coding and handling github PR's and ISSUES, feel free to redirect me to the correct place to post this, I will really appreciaite your help.

Thank's again for your incredible work!!!!!

**Comment by rrdelaney** [comment]
I think this might have been a bug on my end. Can you try it again with version 0.4.0? Thanks!

**Comment by AngelLoredoAlvarez** [comment]
> I think this might have been a bug on my end. Can you try it again with version 0.4.0? Thanks!

I am running version 0.2.0 because newer versions do not work, even though I am running the most recent versions of relay and relay-compiler.

I will downgrade to the versions published in the exmaple of the repo to see if that's the problem.

**Comment by AngelLoredoAlvarez** [comment]
The issue is with my config, I think that is my routing implementation, I'm going with the repo example, closing it, thank you for your time.
