### ISSUE TITLE
Question: clientSideProps not passed to page component?

### ISSUE THREAD

**Issue by Blitz2145** [RevereCRE/relay-nextjs#22]
I was wondering if a page component is supposed to receive props returned from the `clientSideProps` function? I was
expecting them to be spread here: https://github.com/RevereCRE/relay-nextjs/blob/eede2059d6d5e76954606a955f00a5c9e4b0ff02/src/wired/component.tsx#L167

Feel free to close if working as intended.

**Comment by rrdelaney** [comment]
I definitely think this is a bug in the implementation. We really only use it at Revere for redirects, so it seems like this flew under the radar.

**Comment by rrdelaney** [comment]
This should be fixed in 6c56e286c685d3fe65bda06d6ef7c922af752fb5 thanks to @ederski. Will release soon!
