### ISSUE TITLE
Remove default fallback on page load?

### ISSUE THREAD

**Issue by Druddigon** [RevereCRE/relay-nextjs#26]
I noticed that even if I don't specify a fallback as a config parameter for `withRelay`, there's still a default fallback that is showing which is causing a brief flash when I navigate between pages.

I noticed this also on the example in the repo.

Is there a config parameter or recommendation to avoid this?

**Comment by FINDarkside** [comment]
This should now be possible with React 18 (which is still in beta). It doesn't seem to require any changes to this library, simply having your own suspenses at the correct places means you can render a skeleton page before the data is loaded. If your query only includes fragments, it's enough to have suspense wrapping all the components that call `useFragment`.

Unless I'm missing something, the only issue preventing this earlier was that suspense wasn't supported server side in React 17.
