### ISSUE TITLE
nested dynamic routes - how to get the right variable

### ISSUE THREAD

**Issue by philipbalbas** [RevereCRE/relay-nextjs#33]
I have this route `/chapter/[chapterSlug]/topic/[topicSlug]` however the preloadedQuery passes both the `chapterSlug` and `topicSlug` to the query. How do I make it so that only `topicSlug` is passed.

**Comment by rrdelaney** [comment]
Configuring `variablesFromContext` on that page should do the trick!

Something like:

```
export default withRelay(MyPage, {
  /* ... */
  variablesFromContext: ctx => ({ topicSlug: ctx.query.topicSlug }),
});
```

**Comment by philipbalbas** [comment]
thanks that did the trick
