### ISSUE TITLE
Allow disabling of `Suspense` rendering

### ISSUE THREAD

**Issue by matthieu-foucault** [RevereCRE/relay-nextjs#43]
Related to #41 , I have a use case where my page's query will be refetched frequently (I have a filterable table that updated the query string when filters are applied). Rather than having a static fallback for the `Suspense` component, I want to keep rendering the previous page component's (with its props, and maybe an extra `queryIsLoading` prop) while the new query is loading.
We've done that in a previous project (using Relay 10 and the `QueryRenderer`) and it worked well.

I don't think this is feasible right now, and I think that the simplest way to allow this is to add a `renderSuspense` boolean option to the `withRelay` HOC (defaults to `true`). When false, users of the package would have to render their own `Suspense` in `_app` (which I think would allow me to do what I described above).

It's not at the top of my list right now, but I'll look into this in a few weeks and I can contribute to a PR (unless someone else gets to it first :sweat_smile: )

**Comment by rrdelaney** [comment]
This is already possible and we have a similar use-case in our own app, but it's a tough pattern to figure out. They key is using `@arguments` and `@refectable` with a `<Suspense>` around the refetchable fragment. This might not exactly work because it's abstracted from our internal app but the general pattern is:

```tsx
import { useRouter } from 'next/router';
import type { FriendsListQuery } from 'queries/__generated__/FriendsListQuery.graphql';
import type { suspenseTest_FriendsList$key } from 'queries/__generated__/suspenseTest_FriendsList.graphql';
import type { suspenseTest_UserQuery } from 'queries/__generated__/suspenseTest_UserQuery.graphql';
import React, { Suspense, useEffect, useState } from 'react';
import {
  graphql,
  usePreloadedQuery,
  useRefetchableFragment,
} from 'react-relay';
import { RelayProps, withRelay } from 'relay-nextjs';
import { Environment, RecordSource, Store } from 'relay-runtime';
import { useDebounce } from 'use-debounce';

function FriendsList(props: { user: suspenseTest_FriendsList$key }) {
  const [user] = useRefetchableFragment<
    FriendsListQuery,
    suspenseTest_FriendsList$key
  >(
    graphql`
      fragment suspenseTest_FriendsList on User
      @refetchable(queryName: "FriendsListQuery")
      @argumentDefinitions(search: { type: "String" }) {
        friends(first: 50, search: $search) {
          edges {
            node {
              id
              firstName
              lastName
            }
          }
        }
      }
    `,
    props.user
  );

  return (
    <ul>
      {user.friends?.edges?.map((edge) => {
        if (edge?.node == null) return null;
        return (
          <li key={edge.node.id}>
            {edge.node.firstName} {edge.node.lastName}
          </li>
        );
      })}
    </ul>
  );
}

const PageQuery = graphql`
  query suspenseTest_UserQuery($id: ID!, $search: String) {
    user(id: $id) {
      ...suspenseTest_FriendsList @arguments(search: $search)
    }
  }
`;

function UserPage({ preloadedQuery }: RelayProps<{}, suspenseTest_UserQuery>) {
  const query = usePreloadedQuery(PageQuery, preloadedQuery);

  // This is just some code to update the URL search params but not too quickly.
  // You probably should use a real library or something for this.
  const [searchInput, setSearchInput] = useState('');
  const [debouncedSearchInput] = useDebounce(searchInput, 500);
  const router = useRouter();
  useEffect(() => {
    const url = new URL(window.location.href);
    if (!url.searchParams.get('search') && !debouncedSearchInput) return;
    if (url.searchParams.get('search') === debouncedSearchInput) return;

    url.searchParams.set('search', debouncedSearchInput);
    router.replace(url, undefined, { shallow: true });
  }, [debouncedSearchInput, router]);

  // Make sure not to render <Suspense> on the server!
  const [isMounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  if (query.user == null) return null;

  return (
    <div>
      <input
        value={searchInput}
        onChange={(e) => setSearchInput(e.target.value)}
      />

      {isMounted ? (
        <Suspense fallback="Loading friends...">
          <FriendsList user={query.user} />
        </Suspense>
      ) : (
        <FriendsList user={query.user} />
      )}
    </div>
  );
}

export default withRelay(UserPage, PageQuery, {
  /* Your config here */
});

```

With this pattern the only thing that suspends in the refetchable fragment, leaving the rest of the app UI in place! This is also entirely compatible with SSR as all the initial data is fetched on the server. If you're using pagination on your table the same exact approach with with `usePaginationFragment`. Let me know if this works for you!

**Comment by rrdelaney** [comment]
What's cool about this is none of it is Next.js-specific, it's all just React and Relay working well together 😄

**Comment by rrdelaney** [comment]
Going to close this assuming the above comment addressed the issue. Feel free to re-open for more discussion!
