### ISSUE TITLE
Passing error to ErrorComponent

### ISSUE THREAD

**Issue by gio-work** [RevereCRE/relay-nextjs#48]
Specifically for custom ErrorComponent, any reason not to pass the error as a prop here:
https://github.com/RevereCRE/relay-nextjs/blob/main/src/wired/error_boundry.tsx#L27

If not, happy to make a PR to do so 🤙🏻

**Comment by rrdelaney** [comment]
No reason we don’t, would happily accept that PR 😄

**Comment by rrdelaney** [comment]
Fixed by #49 and released in [`v0.8.0`](https://github.com/RevereCRE/relay-nextjs/releases/tag/v0.8.0)
