### ISSUE TITLE
Use with other server side props

### ISSUE THREAD

**Issue by urgent** [RevereCRE/relay-nextjs#62]
next-auth requires I pass a session prop from the server on page load. Otherwise there's a delay as a call is needed to be made client side. Is it possible to provide a server variable alongside relay-nextjs?

```
function Home({ preloadedQuery, session }) {
...
}

export default withRelay(Home, HomeQuery, {
...
})

export async function getInitialProps(context) {
  return {
    props: {
      session: await getSession(context),
    },
  };
}
```

**Comment by rrdelaney** [comment]
Yes, this is possible with the `serverSideProps` option in the page API: https://reverecre.github.io/relay-nextjs/docs/page-api#relayoptions.

Example usage would be something like: 

```tsx
export default withRelay(Home, HomeQuery, {
  // ...
  serverSideProps: async (context) => {
    const { getSession } = await import('my-auth-library');
    const session = await getSession(context);
    return { session };
  },
})
```
