### ISSUE TITLE
WiredComponent.getInitialProps -> Always async

### ISSUE THREAD

**Issue by gio-work** [RevereCRE/relay-nextjs#70]
Hey there,

We noticed that `WiredComponent.getInitialProps` is sync on client and async on server. We would be interested in them being async on either or, since it's technically allowed in [Next.JS](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props)

If this works for y'all, I'm happy to put out a PR.

Thanks!

**Comment by rrdelaney** [comment]
Don't see any reason that it had to be synchronous, would happily accept a PR! Let's make sure that it's backwards compatible and we can return either the value itself or a promise.
