### ISSUE TITLE
Missing configuration @  _document

### ISSUE THREAD

**Issue by LeAlencar** [RevereCRE/relay-nextjs#71]
https://reverecre.github.io/relay-nextjs/docs/configuration#configuring-_document

Missing some tags that are needed in order to work with a custom _document. 

```tsx
return (
  <Html>
    <Head>
      <relayDocument.Script />
    </Head>
    <body>
      <Main />
      <NextScript />
    </body>
  </Html>
);
```

**Comment by rrdelaney** [comment]
The `_document` API had been removed as of 2.0 so this is no longer relevant.
