### ISSUE TITLE
Page component got mount again when using array in query variables

### ISSUE THREAD

**Issue by vip30** [RevereCRE/relay-nextjs#84]
https://github.com/RevereCRE/relay-nextjs/blob/d9ad8aafba17ec8bc61f4bc054e892b6bfbe9b1f/relay-nextjs/src/wired/component.tsx#L88-L92

Seems it's because relay-nextjs is using shallow comparison so if we're using array in the qurey variables, the `useHaveQueryVariablesChanges` will return true by each of the re-render

Is that possible to use deep compare?

**Comment by rrdelaney** [comment]
Thank you for bringing this up! This should be fix with the 2.0 release later today or tomorrow as we now use a deep-equal comparison. Will update here upon release!

**Comment by rrdelaney** [comment]
[`v2.0.0`](https://github.com/RevereCRE/relay-nextjs/releases/tag/v2.0.0) has been released! This should no longer be an issue.
