### ISSUE TITLE
Usage with Nextjs 13 App Router

### ISSUE THREAD

**Issue by elton-okawa** [RevereCRE/relay-nextjs#89]
In Nextjs 13, App Router is stable released as the new approach to deal with routing. Here's some references:
- [Nextjs 13.4 - App Router](https://nextjs.org/blog/next-13-4#nextjs-app-router)
- [App Router Incremental Adoption Guide](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration)
- [Official relay examples using Next 13](https://github.com/relayjs/relay-examples/tree/main/issue-tracker-next-v13)

Current `relay-nextjs` tutorial guide uses `Page Router` approach. I would like to ask some early guidance:
- Is it still possible to use this library?
- What would change?

Thanks in advance!

**Comment by elton-okawa** [comment]
Hi @rrdelaney thanks for the detailed response!

I see, at the moment I don't have any feature in mind.
Being honest, I just came across this library and wanted to try it out with Next.js, then I realized those differences.

May I open up a PR to add this info on `Prerequisites` page? I think more people might stumble on the same question that I had.

**Comment by rrdelaney** [comment]
@elton-okawa Great idea, would love to have something in the README and docs on this 😄

**Comment by redbar0n** [comment]
FWIW, [nextjs-relay-streaming-ssr](https://github.com/tobias-tengler/nextjs-relay-streaming-ssr) is a recent project that uses Next.js 14 App Router (and even React 18 streaming SSR).

**Comment by petrbela** [comment]
Just a note that Relay docs now link to an official example of using SSR with app router (works with getStaticProps/getServerSideProps too). https://github.com/relayjs/relay-examples/tree/main/issue-tracker-next-v13
